### ISSUE TITLE
Rows number

### ISSUE THREAD

**Issue by drew88syn** [lucaseverett/toolbar-dial-chrome#2]
Hi! I really like the idea of this extension, but i have one idea. Can you maybe make a settings for rows number? I love operas speed dial, and the only downside of this extensions, that i cant use 4 rows. Or maybe can you give me some tips, to make it myself 4 row?

**Comment by lucaseverett** [comment]
Hello! I apologize, but I don't understand what you mean. There isn't a limit for how many rows there can be.

**Comment by Rifhifi** [comment]
Hello Lucas, I think there's a confusion between rows and columns.
What he wants is a customizable grid, particularly for columns. 
Let's say if I have 8 bookmarks, I don't like to have them in a single line. I would prefer to have 2 horizontal lines, limited to 4 bookmarks vertically, in the center of the page. With 15 bookmarks, I prefer to have 3 rows * 5 columns grid, etc.

**Comment by lucaseverett** [comment]
@Rifhifi That makes sense now. Thank you for the explanation!

Yes, I will add an option to customize the number of bookmarks per row.

**Comment by lucaseverett** [comment]
@drew88syn @Rifhifi I have a beta/web demo for the ability to set maximum columns. Please feel free to take a look, and let me know if you have any thoughts or feedback. The demo version runs in the browser and has some hard-coded bookmarks for testing.

https://demo-beta.toolbardial.com/

**Comment by drew88syn** [comment]
yep, thats what im looking for :)

**Comment by Rifhifi** [comment]
@lucaseverett  I'm loving it! :)

**Comment by lucaseverett** [comment]
The update for Chrome has been submitted to Google and should be available soon.

Closed by d7c4880f3643408784b9e08844c4087da39ac574.
